image: steveblackburn/comp1110-2019-s2-gitlab-ci:0.1.1

stages:
  - compliance
  - build
  - test

before_script:
  - export PATH_TO_FX=/usr/share/openjfx/lib
  - export JAVAFX_OPTIONS="--module-path $PATH_TO_FX --add-modules javafx.controls,javafx.fxml,javafx.media"
  - export CP=src:/ass2/comp1140-ass2-tests.jar:/ass2/hamcrest-core-1.3.jar:/ass2/junit-4.12.jar


#
# Check compliance of admin files
#
compliance:
  tags:
    - comp1110
  stage: compliance
  script:
    - python3 /validate.py --gitlablogin ${GITLAB_USER_LOGIN} --gitlabuser "${GITLAB_USER_NAME}" --gitlabprojectname "${CI_PROJECT_NAME}" --assignment /compliance-ass2.yml


build:
  tags:
    - comp1110
  stage: build
  script:
    - javac -encoding ISO-8859-1 $JAVAFX_OPTIONS -cp $CP src/comp1140/ass2/*.java src/comp1140/ass2/*/*.java src/comp1140/ass2/*/*/*.java
  artifacts:
    paths:
      - src/comp1140/ass2/*.class
      - src/comp1140/ass2/*/*.class
      - src/comp1140/ass2/*/*/*.class

task2:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1140.ass2.IsStateWellFormedTest
  allow_failure: true

task3:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1140.ass2.IsStateValidTest
  allow_failure: true

task5:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1140.ass2.SelectTilesTest
  allow_failure: true

task6:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1140.ass2.IsActionValidTest
  allow_failure: true

task7:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1140.ass2.ApplyActionTest
  allow_failure: true

task8:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1140.ass2.GetTotalScoreTest
  allow_failure: true

task10:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1140.ass2.GenerateActionTest
  allow_failure: true

## Local Variables:
## mode: yaml
## End:
